// app/feeds/page.tsx
'use client';

import { useState } from "react";

import { Divider } from "@heroui/divider";
import { Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, useDisclosure } from "@heroui/modal";
import { Button } from "@heroui/button";
import {Input} from "@heroui/input";

import { Feeds } from "./compoennts/feeds";
import { Items } from "./compoennts/items";
import { Content } from "./compoennts/content";

import styles from "../../styles/aggregator.module.css"

export default function Aggregator() {
    const {isOpen, onOpen, onOpenChange} = useDisclosure();

    const [activeFeed, setActiveFeed] = useState(0);
    const [currentItem, setCurrentItem] = useState([]);
    const [articles, setArticles] = useState([
        {
            feed: "Feed Title",
            title: "Article Title",
            content: "Culpa proident magna tempor enim duis enim esse excepteur commodo. Non fugiat do irure incididunt consectetur Lorem est id nulla.",
            time: "Some time ago"
        },
        {
            feed: "Feed Title",
            title: "Another article Title",
            content: "Aliqua id reprehenderit reprehenderit adipisicing sit minim ipsum eiusmod quis. Officia sit non officia excepteur occaecat est cupidatat nisi mollit.",
            time: "Some time ago"
        }
    ])

    return (
        <>            
            <div className={`${styles.all}`}>
                <span className={`${styles.feeds}`}>
                    <Feeds onOpen={onOpen} activeFeed={activeFeed} setActiveFeed={setActiveFeed}  />
                </span>

                <Divider orientation="vertical" />

                <span className={`${styles.items}`}>
                    <Items currentItem={currentItem} setCurrentItem={setCurrentItem} />
                </span>

                <Divider orientation="vertical" />

                <span className={`${styles.content}`}>
                    <Content currentItem={currentItem} articles={articles} />
                </span>
            </div>

            <Modal isOpen={isOpen} onOpenChange={onOpenChange}>
                <ModalContent>
                {(onClose) => (
                    <>
                    <ModalHeader>New RSS Feed</ModalHeader>

                    <ModalBody>
                        <Input label="Feed name" />

                        <Input label="Feed URL" />
                    </ModalBody>

                    <ModalFooter>
                        <Button color="danger" variant="light" onPress={onClose}>
                        Cancel
                        </Button>

                        <Button color="primary" onPress={onClose}>
                        Add Feed
                        </Button>
                    </ModalFooter>
                    </>
                )}
                </ModalContent>
            </Modal>
        </>
    )
}

// app/pages/feeds.vue
<script>

</script>

<template>
    <div id="container">
        <div id="feeds">
            <div class="feed">
                <h3>Feed #1</h3>
            </div>

            <div class="feed">
                <h3>Feed #2</h3>
            </div>
        </div>

        <div id="items">
            <div class="item">
                <h3>Some title</h3>

                <p>Incididunt culpa eu dolor anim sit proident Lorem aute quis. Est reprehenderit anim magna deserunt ipsum mollit adipisicing esse enim.</p>
            </div>

            <div class="item">
                <h3>Some title</h3>

                <p>Incididunt culpa eu dolor anim sit proident Lorem aute quis. Est reprehenderit anim magna deserunt ipsum mollit adipisicing esse enim.</p>
            </div>
        </div>

        <div id="content">
            <p>article content</p>
        </div>
    </div>
</template>

<style>
    @import url("~/assets/styles/feeds.css")
</style>
